### ISSUE TITLE
Administrar sala

### ISSUE THREAD

**Issue by ygortgaleno** [fga-eps-mds/2019.1-StreamUs-Backend#13]
**Eu como** usuário
**Desejo** administrar sala
**Para que** eu possa criar ambientes fechados de musica no aplicativo

**Descrição:**
A criação da sala irá servir para que pessoas compartilhem da mesma fila de musica, e a exclusão para excluir a sala

**Critérios de aceitação**
 - Criar sala no aplicativo
 - Excluir sala no aplicativo

**Task**
- [x] Criar endpoint POST de sala
- [x] Criar endpoint DELETE de sala
- [x] Fazer teste unitários
