### ISSUE TITLE
Administrar playlist colaborativa dentro de uma sala

### ISSUE THREAD

**Issue by ygortgaleno** [fga-eps-mds/2019.1-StreamUs-Backend#16]
**Eu como** Usuário
**Desejo** administrar playlist colaborativas
**Para que** seja possível administrar playlists colaborativas dentro de uma sala do aplicativo

**Descrição:**
Essa issue tem como finalidade a administração de playlist colaborativa dentro de uma sala.

**Critérios de aceitação**
- Criação de uma playlist colaborativa
- Seleção de uma playlist colaborativa
- Exclusão de uma playlist colaborativa

**Task**
- [x] criar endpoint POST de playlist colaborativa
- [x] criar endpoint GET de playlist colaborativa
- [x] criar endpoint DELETE de playlist colaborativa  
- [x] Teste unitário

**Comment by oliveiraMarcelo** [comment]
Testes estão como dividas técnicas
