### ISSUE TITLE
Administrar fila de músicas dentro de uma playlist colaborativa

### ISSUE THREAD

**Issue by ygortgaleno** [fga-eps-mds/2019.1-StreamUs-Backend#18]
**Eu como** Usuário
**Desejo** administrar as músicas da fila
**Para que** seja possível editar a fila de reprodução

**Descrição:**
Essa issue tem como objetivo poder administrar as músicas dentro da playlist colaborativa

**Critérios de aceitação**
- Adicionar música na fila de reprodução
- Alterar posição da música na fila de reprodução
- Remover música na fila de reprodução

**Task**
- [x] criar endpoint POST de música na fila de reprodução
- [x] criar endpoint PUT de música na fila de reprodução
- [x] criar endpoint DELETE de música na fila de reprodução
- [ ] Teste unitário

**Comment by iagoomr** [comment]
Issue moved to Frontend

**Comment by iagoomr** [comment]
Issue moved to [fga-eps-mds/2019.1-StreamUs-Frontend #16](https://github.com/fga-eps-mds/2019.1-StreamUs-Frontend/issues/16) via [**ZenHub**](https://www.zenhub.com/)
