### ISSUE TITLE
Criar componente de votação para remoção de música em uma playlist

### ISSUE THREAD

**Issue by ygortgaleno** [fga-eps-mds/2019.1-StreamUs-Backend#19]
**Eu como** usuário
**Desejo**  votar na música para que ela seja removida da playlist
**Para que**  ela seja retirada da ordem de execução

**Descrição:**
O usuário irá interagir para iniciar uma votação para remover a música da playlist

**Critérios de aceitação**
 - Votar para remover a música
 - Excluir da playlist se aprovada por mais de 60% da sala

**Observações**
 - O voto do administrador da sala tem peso 2

**Task**
- [ ] criar botão para excluir música
- [ ] criar componente de votação
- [ ] notificar os membros da sala

**Comment by oliveiraMarcelo** [comment]
issue [#8](https://github.com/fga-eps-mds/2019.1-StreamUs-Frontend/issues/8) do frontend
