### ISSUE TITLE
Politicas para contribuições

### ISSUE THREAD

**Issue by oliveiraMarcelo** [fga-eps-mds/2019.1-StreamUs-Backend#4]
**Eu como** Scrum Master
**Desejo** Criar uma politica de git
**Para que** Haja uma padronização das contribuições

**Descrição:**
Essa issue tem como finalidade criar uma padronização no uso de commits e de branchs do projeto.

**Task:**
- [x] Explicar WIP(branchs)
- [x] Explicar #Fix
- [x] Criar/Explicar politica de branchs
- [x] Criar/Explicar politica de commits
- [x] Explicar como será a escrita de issues
