### ISSUE TITLE
Elaborar Backlog do backend

### ISSUE THREAD

**Issue by oliveiraMarcelo** [fga-eps-mds/2019.1-StreamUs-Backend#7]
**Eu como** Prodcut Owner
**Desejo** Criar o Backlog do produto
**Para que** Se tenha todas as funcionalidades listadas

**Descrição**
Essa issue tem como finalidade ter a versão inicial do backlog do produto.

**Tasks**
- [x] Elaborar versão inicial do backlog
- [x] Elicitar requisitos do produto
- [ ] Validar backlog com professor(a)/coach
